name: 'build-test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifact to delete
        run: |
          echo $(date) > date.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: date.txt
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: |
          rm package-lock.json
          export NODE_OPTIONS=--openssl-legacy-provider
          (
            set -x
            yarn
            # yarn run all
            yarn run build
            yarn run format
            # yarn run lint
            yarn run pack
            yarn run test
            set +x
          )
          git status
  test:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        id: clean
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: '2minutes'
      - run: |
          echo ${{ steps.clean.outputs.deleted-artifacts }}
