name: 'build-test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifact to delete
        run: |
          echo $(date) > date.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: date.txt
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: |
          rm package-lock.json
          # export NODE_OPTIONS=--openssl-legacy-provider
          yarn
          # yarn upgrade
          yarn run all
  test:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: '2minutes'
